### Criar order
POST http://localhost:8080/v1/order
Content-Type: application/json

{
  "name": "Fernando",
  "amount": 123.45,
  "status": "pending"
}

### Listar orders
GET http://localhost:8080/v1/order
